name: Run JS Tests & Check Coverage

on: push

jobs:
  run-js-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
         node-version: '16.x'
         registry-url: 'https://registry.npmjs.org'
      - run: npm install --include=dev
      - run: npm run compile
      - run: npm link #create link for embedded player below
      - run:
        | 
          cd src/main/js/player
          npm install 
          npm link @antmedia/webrtc_adaptor #use the link 
          npm run compile
          cd -
      - run: npm run test
      - run: npm run codecov